### PR TITLE
Added SAS Viya 3.5

### PR DESCRIPTION
**Pull request by asieira**
Submitted after testing and confirmation from SAS support during an engagement with a financial services customer. SAS representative added IMDSv2 support has been requested by multiple customers, but is still not available.

### CODE REVIEW

**Comment by 0xdabbad00** [comment]
Is Viya 3.5 an older version? I want to ensure I don't add an older product that can be updated to a newer version to obtain IMDSv2 support.

**Comment by asieira** [comment]
I specified the version because that is what the customer is running and we tested directly. But SAS support did not mention upgrading as an option to fix the issue, so I'm assuming no versions support it yet.

**Comment by asieira** [comment]
I'll try to get confirmation whether any version exists that supports IMDSv2 and update this as soon as I know more.

**Comment by asieira** [comment]
@0xdabbad00 got confirmation from SAS support that there are no versions that support IMDSv2.

**Comment by 0xdabbad00** [comment]
Thank you @asieira !

**Pull request merged**
